### ISSUE TITLE
Promise 2.3.0 installation fails

### ISSUE THREAD

**Issue by bryanapperson** [syrusakbary/promise#94]
```
$ pip install promise
Looking in indexes: http://pypi/simple
Collecting promise
  Downloading http://pypil/packages/promise/2.3/promise-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1d524305/promise/setup.py", line 11, in <module>
        version = __import__("promise").get_version()
    ModuleNotFoundError: No module named 'promise'
```

I also see this behavior with 2.2.0.

**Comment by bryanapperson** [comment]
```
python --version
Python 3.7.4
```

**Comment by bryanapperson** [comment]
This looks like an environment/mirror issue. Closing.
